config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  
  resources :charges
  resources :reviews, only: %i[edit update destroy]
  get 'reviews/new/:id', to: 'reviews#new', as: :new_review
  post 'reviews/post/:id', to: 'reviews#create', as: :reviews
  get 'reviews/:product_id', to: 'reviews#index', as: :all_review

  get 'review', to: 'reviews#show', as: :your_reviews

  get 'product/sort/:category_type' , to: 'products#sort' , as: :product_sort
  resources :addresses
  get 'wishlists/show'
  get 'transactions/new'
  get 'contacts/index'
  get 'search/index'
  get 'carts/show'
  get 'carts/address/:id', to: 'carts#address_show_add', as: :address_show_add
  get 'carts/payment_option/:id/:quantity/:total', to: 'carts#payment_option', as: :payment
  get 'carts/payment_success/:id/:quantity', to: 'carts#payment_success', as: :payment_success
  get 'user/orders', to: 'users#order', as: :order

  get 'supplier/orders', to: 'suppliers#order_mgmt', as: :order_mgmt
  get 'order/export' , to: 'suppliers#export_csv' , as: :export_csv
  get 'supplier/delivered/orders', to: 'suppliers#delivered_product', as: :delivered_product
  
  post 'supplier/delivered/orders/:product_id', to: 'suppliers#delivered_create', as: :delivered_products
  
  delete 'user/order/:id/:user_id', to: 'orders#destroy', as: :order_cancel

  devise_for :suppliers

  get 'ofs/products' , to: 'suppliers#ofs_products' , as: :ofs_products

  # resources :products do
  #   collection do
  #     get 'category/:category_name', to: 'products#product_category_index', as: :product_category
  #   end
  # end

  get 'products/:category_type', to: 'products#category', as: :show_category_product
  get 'product/:id', to: 'products#show', as: :show_product
  get 'productss/:brand/:category', to: 'products#brand', as: :show_brand_product
  get 'productss/:name/:min_price/:mid_price', to: 'products#price', as: :price_product

  get 'product', to: 'products#new', as: :new_product
  post 'products', to: 'products#create', as: :products

  resources :categories

  resources :products, only: %i[edit update index destroy]

  get 'search', to: 'search#search_product', as: :product_search

  resources :wishlists, only: [:show]
  get 'product/wishlists/:product_id', to: 'wishlists#create', as: :add_to_wishlist
  delete 'wishlists/:product_id', to: 'wishlists#destroy', as: :delete_from_wishlist

  resources :transactions, only: %i[new create]

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/index'
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :show, only: %i[address_show_add payment_success payment_option]

  def show
    @order_details = OrderDetail.new
  
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
    @cart_total_price = 0
    @cart_discount = 0
    @cart_products.each do |product|
      @cart_total_price += product.price
      @cart_discount += product.discount
    end
  end

  def add
    $redis.sadd current_user_cart, params[:product_id]
    redirect_to action: 'show'
    # render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id]
    redirect_to action: 'show'
    # render json: current_user.cart_count, status: 200
  end

  def address_show_add
    #binding.pry
    @address = Address.where(user_id: current_user.id)
    @user = User.find(current_user.id)
   
  end

  def new_address
    @user = User.find(current_user.id)
  end

  def payment_option; end

  def payment_success
    # while(params[:id].count)
    product_ids = params[:id].split('/')
    @user = User.find(current_user.id)
    @order = current_user.orders.build
    product_ids.each do |id|
      puts "ppppppp#{params[:quantity]}"
      @product = Product.find(id)
     
     @order.save
     
      #@order = Order.new(user_id: current_user.id, product_id: id, quantity: params[:quantity])
      @order_details = OrderDetail.new(product_id: id,order_id: @order.id,name:@product.name,price: @product.price,color:@product.color,size:@product.size,discount:@product.discount,total:params[:total], quantity: params[:quantity])
     
      unless @order_details.save
      
     
      OrderMailer.with(user: @user).order_email.deliver_now
      @products = Product.find(id)
      $redis.srem current_user_cart, id
      @products.decrement!(:stock, by= params[:quantity].to_i)
      # 	render "payment_success"
      # else
      # 	render plain: @order.product_id
      # end
      else
       #@order.destroy 
   
    end
  end
end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end

  def order_params
    params.require(:order).permit.merge(user_id: current_user.id, product_id: params[:id])
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/_address.html.erb
<div>
	<%if @address.present? %>
	<div class="d-flex flex-column justify-content-center">
		<div class="d-flex flex-column">
			<h4>Conatct details</h4>
			<%=@user.name%> <br />
			<%= @user.contact_no %>
		</div>

		<div class="my-1">
			<h4>Address</h4>
			<% @address.each do |address|%>
			<div class="d-flex flex-column">
				<div><%=address.address%></div>
				<div> <%=address.area%> <%=address.city%></div>
				<%=address.state%>
				pincode: <%= address.pincode %>
			</div>
			<%end%>
		</div>
		<%else%>
		<h3>Address not found</h3>
		<%end%>
	</div>
</div>

app/views/carts/address_show_add.html.erb
<%= render 'address' %>
<div class="button banner_button">
	<%= link_to "Change or Add address" , new_address_path %>
</div>
<hr />
<div>
	<h3>price details(<%=current_user.cart_count%> item)</h3>
	<div class="row">
		<div class="col-1">MRP :</div>
		<div class="col-3"><%= current_user.total_price %></div>
	</div>
		<div class="row">
		<div class="col-1">Quantity :</div>
		<div class="col-3"><%= params[:quantity] %></div>
	</div>
	<div class="row">
		<div class="col-1">Discount :</div>
		<div class="col-3"><%= @cart_discount %></div>
	</div>
	<hr />
	<div>
		<div class="row">
			<div class="col-1">Total :</div>
			<% @total = current_user.total_price - @cart_discount %>
			<div class="col-3"><%= @total*params[:quantity].to_i %></div>
		</div>
		<div class="row">
			<div class="col-2 button banner_button mx-2 text-align-center"><%= link_to "view details" , carts_show_path%></div>
			<div class="col-2 button banner_button text-center"><%= link_to "confirm" , payment_path(@cart_products,params[:quantity],@total) %></div>
		</div>
	</div>
</div>

app/views/carts/payment_option.html.erb
<center>
<div class="">
<div> <%= link_to "Pay on delivery" , payment_success_path(@cart_products,params[:quantity]) %> </div>

<div>
	<br>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
   <!--  <label class="amount">
      <span>Amount: $5.00</span>
    </label> -->
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription"   data-email="<%= current_user.email %>" data-amount="<%=params[:total]%>" data-locale="auto"></script>
<% end %>

</div>
</div>
</center>

app/views/carts/payment_success.html.erb
<div>
<div class="d-flex flex-column align-items-center  justify-content-center">
	<h2>Thank you!!</h2>
	<h3 class="text-primary">you order is confirmed!!</h3>
</div>
<center>
<div class="button banner_button ">
	<%= link_to "view order ", order_path %>
</div>
</center>
</div>

app/views/carts/show.html.erb
<div class="cart_section">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <div class="cart_container">
          <div class="cart_title">Shopping Cart</div>
          <% @cart_products.each do |product|%>
          <div class="cart_items">
            <ul class="cart_list">
              <li class="cart_item clearfix">
                <div class="cart_item_image">
                  <% product.images.each do |image| %> <%=link_to product do%>
                  <div class="my-5">
                    <%= image_tag image,:class => "img-fluid" %>
                  </div>
                </div>
                <%end%> <%end%>
                <div
                  class="cart_item_info d-flex flex-md-row flex-column justify-content-between"
                >
                  <div class="cart_item_name cart_info_col">
                    <div class="cart_item_title">Name</div>
                    <div class="cart_item_text"><%= product.name %></div>
                  </div>
                  <div class="cart_item_color cart_info_col">
                    <div class="cart_item_title">Color</div>
                    <div class="cart_item_text">
                      <span style="background-color: #999999"></span><%=
                      product.color %>
                    </div>
                  </div>
                 
 
                  <div class="cart_item_price cart_info_col">
                    <div class="cart_item_title">Price</div>
                    <div class="cart_item_text"><%= product.price %></div>
                  </div>
                   <%= form_with url:address_show_add_path(@cart_products),local:true , method: :get do |f|%>
                  <div class="cart_item_quantity cart_info_col">
                    <div class="cart_item_title ml-4">Quantity</div>
                    <div class="cart_item_text ml-4">
                    <%= f.number_field "quantity" ,max: product.stock, min:1%>
                  </div>
                  </div>
                    
                  <%end%>
                  <div class="d-flex">
                    <%=link_to "Remove From Cart",remove_from_cart_path(product), class: "remove" , method: :put%>
                  </div>
                </div>
              </li>
            </ul>
            
          </div>
        </div>
      

        <% end %>
        <!-- Order Total -->
        <div class="order_total">
          <div class="order_total_content text-md-right">
            <div class="order_total_title">Order Total:</div>
            <div class="order_total_amount"><%= @cart_total_price %></div>
          </div>
        </div>
        <%=link_to "Checkout", address_show_add_path(@cart_products), class: "d-flex justify-content-right banner-button button" unless @cart_products.blank?%>
      
      </div>
    </div>
  </div>
</div>

<!-- Newsletter -->

<div class="newsletter">
  <div class="container">
    <div class="row">
      <div class="col">
        <div
          class="newsletter_container d-flex flex-lg-row flex-column align-items-lg-center align-items-center justify-content-lg-start justify-content-center"
        >
          <div class="newsletter_title_container">
            <div class="newsletter_icon">
              <img src="images/send.png" alt="" />
            </div>
            <div class="newsletter_title">Sign up for Newsletter</div>
            <div class="newsletter_text">
              <p>...and receive %20 coupon for first shopping.</p>
            </div>
          </div>
          <div class="newsletter_content clearfix">
            <form action="#" class="newsletter_form">
              <input
                type="email"
                class="newsletter_input"
                required="required"
                placeholder="Enter your email address"
              />
              <button class="newsletter_button">Subscribe</button>
            </form>
            <div class="newsletter_unsubscribe_link">
              <a href="#">unsubscribe</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 footer_col">
        <div class="footer_column footer_contact">
          <div class="logo_container">
            <div class="logo"><a href="#">OneTech</a></div>
          </div>
          <div class="footer_title">Got Question? Call Us 24/7</div>
          <div class="footer_phone">+38 068 005 3570</div>
          <div class="footer_contact_text">
            <p>17 Princess Road, London</p>
            <p>Grester London NW18JR, UK</p>
          </div>
          <div class="footer_social">
            <ul>
              <li>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-twitter"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-youtube"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-google"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-vimeo-v"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-2 offset-lg-2">
        <div class="footer_column">
          <div class="footer_title">Find it Fast</div>
          <ul class="footer_list">
            <li><a href="#">Computers & Laptops</a></li>
            <li><a href="#">Cameras & Photos</a></li>
            <li><a href="#">Hardware</a></li>
            <li><a href="#">Smartphones & Tablets</a></li>
            <li><a href="#">TV & Audio</a></li>
          </ul>
          <div class="footer_subtitle">Gadgets</div>
          <ul class="footer_list">
            <li><a href="#">Car Electronics</a></li>
          </ul>
        </div>
      </div>

      <div class="col-lg-2">
        <div class="footer_column">
          <ul class="footer_list footer_list_2">
            <li><a href="#">Video Games & Consoles</a></li>
            <li><a href="#">Accessories</a></li>
            <li><a href="#">Cameras & Photos</a></li>
            <li><a href="#">Hardware</a></li>
            <li><a href="#">Computers & Laptops</a></li>
          </ul>
        </div>
      </div>

      <div class="col-lg-2">
        <div class="footer_column">
          <div class="footer_title">Customer Care</div>
          <ul class="footer_list">
            <li><a href="#">My Account</a></li>
            <li><a href="#">Order Tracking</a></li>
            <li><a href="#">Wish List</a></li>
            <li><a href="#">Customer Services</a></li>
            <li><a href="#">Returns / Exchange</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">Product Support</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Copyright -->

<div class="copyright">
  <div class="container">
    <div class="row">
      <div class="col">
        <div
          class="copyright_container d-flex flex-sm-row flex-column align-items-center justify-content-start"
        >
          <div class="copyright_content">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
          
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </div>
          <div class="logos ml-sm-auto">
            <ul class="logos_list">
              <li>
                <a href="#"><img src="images/logos_1.png" alt="" /></a>
              </li>
              <li>
                <a href="#"><img src="images/logos_2.png" alt="" /></a>
              </li>
              <li>
                <a href="#"><img src="images/logos_3.png" alt="" /></a>
              </li>
              <li>
                <a href="#"><img src="images/logos_4.png" alt="" /></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>