config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  
  resources :charges
  resources :reviews, only: %i[edit update destroy]
  get 'reviews/new/:id', to: 'reviews#new', as: :new_review
  post 'reviews/post/:id', to: 'reviews#create', as: :reviews
  get 'reviews/:product_id', to: 'reviews#index', as: :all_review

  get 'review', to: 'reviews#show', as: :your_reviews

  get 'product/sort/:category_type' , to: 'products#sort' , as: :product_sort
  resources :addresses
  get 'wishlists/show'
  get 'transactions/new'
  get 'contacts/index'
  get 'search/index'
  get 'carts/show'
  get 'carts/address/:id', to: 'carts#address_show_add', as: :address_show_add
  get 'carts/payment_option/:id/:quantity/:total', to: 'carts#payment_option', as: :payment
  get 'carts/payment_success/:id/:quantity', to: 'carts#payment_success', as: :payment_success
  get 'user/orders', to: 'users#order', as: :order

  get 'supplier/orders', to: 'suppliers#order_mgmt', as: :order_mgmt
  get 'order/export' , to: 'suppliers#export_csv' , as: :export_csv
  get 'supplier/delivered/orders', to: 'suppliers#delivered_product', as: :delivered_product
  
  post 'supplier/delivered/orders/:product_id', to: 'suppliers#delivered_create', as: :delivered_products
  
  delete 'user/order/:id/:user_id', to: 'orders#destroy', as: :order_cancel

  devise_for :suppliers

  get 'ofs/products' , to: 'suppliers#ofs_products' , as: :ofs_products

  # resources :products do
  #   collection do
  #     get 'category/:category_name', to: 'products#product_category_index', as: :product_category
  #   end
  # end

  get 'products/:category_type', to: 'products#category', as: :show_category_product
  get 'product/:id', to: 'products#show', as: :show_product
  get 'productss/:brand/:category', to: 'products#brand', as: :show_brand_product
  get 'productss/:name/:min_price/:mid_price', to: 'products#price', as: :price_product

  get 'product', to: 'products#new', as: :new_product
  post 'products', to: 'products#create', as: :products

  resources :categories

  resources :products, only: %i[edit update index destroy]

  get 'search', to: 'search#search_product', as: :product_search

  resources :wishlists, only: [:show]
  get 'product/wishlists/:product_id', to: 'wishlists#create', as: :add_to_wishlist
  delete 'wishlists/:product_id', to: 'wishlists#destroy', as: :delete_from_wishlist

  resources :transactions, only: %i[new create]

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/index'
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/suppliers_controller.rb
# frozen_string_literal: true

class SuppliersController < ApplicationController
  def order_mgmt
    @products =	current_supplier.products.joins(:order_details,[{orders: :user}]).pluck('users.name,products.name,order_details.created_at,products.id,users.id,order_details.order_status')
 		@order_detail = OrderDetail.new
    respond_to do |format|
    format.html
    format.pdf do
    render pdf: "suppliers/orders.pdf",
    template: "suppliers/order_mgmt.pdf.erb",
    layout: 'application.html'
    end
    end
  end

  def export_csv
    @products =	current_supplier.products.joins(:order_details,[{orders: :user}]).pluck('users.name,products.name,order_details.created_at,products.id,users.id,order_details.order_status')
 	  respond_to do |format|
    format.html {}
    format.csv { send_data @products.to_csv ,filename: "order_details-#{Date.today}.csv"
    }
    end  
  end

  def delivered_product
    @products =	current_supplier.products.joins(:order_details,[{orders: :user}]).pluck('users.name,products.name,order_details.created_at,products.id,users.id,order_details.order_status')
  end

  def delivered_create
  	@order = OrderDetail.find_by(product_id: params[:product_id])
  	if @order.update(order_status: true, delivery_date: Date.today)
  		redirect_to delivered_product_path
  	end
  end

  def ofs_products
  	@products = Product.where(supplier_id: current_supplier.id, stock: 0)
  	render "supplier/out_of_stock_products"
  end
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/views/supplier/_index.html.erb
<% unless current_supplier.admin? %>
<%= render 'supplier/navbar' %>
	<div class="d-flex justify-content-around">
		<div>
			<%= column_chart Product.where(supplier_id:
			current_supplier.id).group_by_day(:created_at).count %>
		</div>
		<div>
			<%= bar_chart Product.where(supplier_id:
			current_supplier.id).joins(:category).group(:category_type).count %>
		</div>
	</div>
</nav>

<% else %> <%end%>

app/views/supplier/_navbar.html.erb
<nav class="main_nav">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="main_nav_content d-flex flex-row">
					<!-- Categories Menu -->

					<div class="cat_menu_container">
						<div
							class="cat_menu_title d-flex flex-row align-items-center justify-content-start"
						>
							<div class="cat_burger">
								<span></span><span></span><span></span>
							</div>
							<div class="cat_menu_text">categories</div>
						</div>

						<ul class="cat_menu">
							<li>
								<%= link_to "Product Management" , products_path %>
								<i class="fas fa-chevron-right ml-auto"></i>
							</li>
							<li>
								<%= link_to "Out of stock products" , ofs_products_path %>
								<i class="fas fa-chevron-right"></i>
							</li> 
							<li>
								<%= link_to "Order Management" , order_mgmt_path %>
								<i class="fas fa-chevron-right ml-auto"></i>
							</li>
							<li>
								<%= link_to "Delivered Products" , delivered_product_path %>
								<i class="fas fa-chevron-right ml-auto"></i>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/supplier/out_of_stock_products.html.erb
<%= render 'supplier/navbar' %>
<div>
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">product name</th>
					<th scope="col">stock</th>
				
					
					<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				<% @products.each do |product|%>
				<tr>

					<th scope="row"></th>
					<td><%=product.name%></td>
					<td><%=product.stock%></td>
					<td><%=link_to "edit" , edit_product_path(product)%></td>
				</tr>
				<%end%>
			</tbody>
		</table>
	</div>

app/views/supplier/search.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">description</th>
      <th scope="col">price</th>
      <th scope="col">Color</th>
      <th scope="col">Stock</th>
      <th scope="col">Status</th>
      <th scope="col">Discount</th>
      <th scope="col">Brand</th>
      
      <th scope="col">Model</th>
      <th scope="col">Model Year</th>
      <th scope="col">Connector type</th>
      <th scope="col">Memory Storage</th>
      <th scope="col">Operating System</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  	<% @products.each do |product| %>
    
    <tr>
      <th scope="row"><%= product.id %></th>
      <td><%= product.name%></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.color %></td>
      <td><%= product.stock %></td>
      <td><%= product.status %></td>
      <td><%= product.discount %></td>
      <td><%= product.brand %></td>
      <td><%= product.model %></td>
      <td><%= product.model_year %></td>
      <td><%= product.connector_type %></td>
      <td><%= product.memoryStorage %></td>
      <td><%= product.operatingSystem %></td>
      <td><%=link_to "edit" , edit_product_path(product)%></td>
      <td><%=link_to "delete" , product_path(product), method: :delete, data: {confirm: "Are you Sure?"}%></td>
      
      
    </tr>
   
<%end%>
  </tbody>
</table>