config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  
  resources :charges
  resources :reviews, only: %i[edit update destroy]
  get 'reviews/new/:id', to: 'reviews#new', as: :new_review
  post 'reviews/post/:id', to: 'reviews#create', as: :reviews
  get 'reviews/:product_id', to: 'reviews#index', as: :all_review

  get 'review', to: 'reviews#show', as: :your_reviews

  get 'product/sort/:category_type' , to: 'products#sort' , as: :product_sort
  resources :addresses
  get 'wishlists/show'
  get 'transactions/new'
  get 'contacts/index'
  get 'search/index'
  get 'carts/show'
  get 'carts/address/:id', to: 'carts#address_show_add', as: :address_show_add
  get 'carts/payment_option/:id/:quantity/:total', to: 'carts#payment_option', as: :payment
  get 'carts/payment_success/:id/:quantity', to: 'carts#payment_success', as: :payment_success
  get 'user/orders', to: 'users#order', as: :order

  get 'supplier/orders', to: 'suppliers#order_mgmt', as: :order_mgmt
  get 'order/export' , to: 'suppliers#export_csv' , as: :export_csv
  get 'supplier/delivered/orders', to: 'suppliers#delivered_product', as: :delivered_product
  
  post 'supplier/delivered/orders/:product_id', to: 'suppliers#delivered_create', as: :delivered_products
  
  delete 'user/order/:id/:user_id', to: 'orders#destroy', as: :order_cancel

  devise_for :suppliers

  get 'ofs/products' , to: 'suppliers#ofs_products' , as: :ofs_products

  # resources :products do
  #   collection do
  #     get 'category/:category_name', to: 'products#product_category_index', as: :product_category
  #   end
  # end

  get 'products/:category_type', to: 'products#category', as: :show_category_product
  get 'product/:id', to: 'products#show', as: :show_product
  get 'productss/:brand/:category', to: 'products#brand', as: :show_brand_product
  get 'productss/:name/:min_price/:mid_price', to: 'products#price', as: :price_product

  get 'product', to: 'products#new', as: :new_product
  post 'products', to: 'products#create', as: :products

  resources :categories

  resources :products, only: %i[edit update index destroy]

  get 'search', to: 'search#search_product', as: :product_search

  resources :wishlists, only: [:show]
  get 'product/wishlists/:product_id', to: 'wishlists#create', as: :add_to_wishlist
  delete 'wishlists/:product_id', to: 'wishlists#destroy', as: :delete_from_wishlist

  resources :transactions, only: %i[new create]

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/index'
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true
require 'elasticsearch/model'
class Product < ApplicationRecord
  #  include Elasticsearch::Model
  #  include Elasticsearch::Model::Callbacks
  visitable 
  
  has_many :events, class_name: "Ahoy::Event"
  belongs_to :category
  delegate :category_type , to: :category
  belongs_to :supplier
  has_and_belongs_to_many :wishlists
  has_many :order_details
  has_many :orders, through: :order_details,dependent: :destroy
  has_many :users, through: :orders
  has_many_attached :images
  has_many :reviews
  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      'Remove from'
    else
      'Add to'
    end
  end

  rails_admin do
    edit do
      include_all_fields
      field :images do
      end
    end
  end

  rails_admin do
    show do
      include_all_fields
      field :images do
      end
    end
  end
end
# Product.__elasticsearch__.create_index!
# Product.import

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_product, only: %i[destroy show edit update]
  # before_action :categories
  after_action :track_action , only: %i[show]

  

  def categories
    @categories = Category.pluck(:category_type)
  end

  def sort
    if params[:order] && params[:order] == "Ratings High to Low"
      @products=Product.includes(:category).where(categories: { category_type: params[:category_type] }).left_outer_joins(:reviews).order("reviews.rating DESC NULLS LAST")
    elsif params[:order] && params[:order] == "Ratings Low to High"
      @products=Product.includes(:category).where(categories: { category_type: params[:category_type] }).left_outer_joins(:reviews).order("reviews.rating")
    end
  end

  def new
    @categories_all = Category.all
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    # @product.images.variant(resize: "400x300^", crop: '400x300+0+0')
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @categories_all = Category.all
  end

  def update
    @categories_all = Category.all
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def index
    @products = current_supplier.products.page(params[:page]).per(10)
    render 'product_show'
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def category
    @products_count = Product.includes(:category).where(categories: { category_type: params[:category_type] }).count
    @products = Product.includes(:category).where(categories: { category_type: params[:category_type] }).page(params[:page]).per(7)
    @categories = Category.pluck(:category_type)
    @min_price = Product.minimum(:price)
    @max_price = Product.maximum(:price)
  end

  def show
    # @product = Product.find(params[:id])
    @order = Order.new
    @review = Review.where(product_id: params[:id]).joins(:user)
    @avg_rating = Review.where(product_id: params[:id]).average(:rating)
    @cart_action = @product.cart_action current_user.try :id
  end

  def brand
    @categories = Category.pluck(:category_type)
    @products = Product.where(brand: params[:brand]).includes(:category).where(categories: { category_type: params[:category] }).page(params[:page]).per(7)
  end

  def price
    @categories = Category.pluck(:category_type)
    @min_price = Product.minimum(:price)
    @max_price = Product.maximum(:price)
    @products = Product.where(price: (params[:min_price]..params[:mid_price])).includes(:category).where(categories: { category_type: params[:name] }).page(params[:page]).per(7)
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :color, :category_id, :description, :brand, :stock, :status, :model, :price, :images,
                                    :size).merge(supplier_id: current_supplier.id)
  end

  protected

  def track_action
    ahoy.track "Ran action", request.path_parameters
  end
  
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_brand.html.erb
<!-- Product Item -->
<% @products.each do |product|%>
<div class="product_item">
	<div class="product_border"></div>
	<div
		class="product_image d-flex flex-column align-items-center justify-content-center"
	>
		<% product.images.each do |image| %> <%= link_to (image_tag image,:class =>
		"img-fluid" ), show_product_path(product) %> <% end %>
	</div>
	<div class="product_content">
		<div class="product_price"><%= product.price %></div>
		<div class="product_name">
			<div><a href="#" tabindex="0"><%= product.name %></a></div>
		</div>
	</div>
</div>

<%end%>

<!-- Shop Page Navigation -->

app/views/products/_price.html.erb
<% @products.each do |product|%>

<div class="product_item">
	<div class="product_border"></div>
	<div
		class="product_image d-flex flex-column align-items-center justify-content-center"
	>
		<% product.images.each do |image| %> <%= link_to (image_tag image,:class =>
		"img-fluid" ), show_product_path(product) %> <% end %>
	</div>
	<div class="product_content">
		<div class="product_price"><%= product.price %></div>
		<div class="product_name">
			<div><a href="#" tabindex="0"><%= product.name %></a></div>
		</div>
	</div>
</div>

<%end%>

app/views/products/_sort.html.erb
<!-- Product Item -->
<% @products.each do |product|%>
<div class="product_item">
	<div class="product_border"></div>
	<div
		class="product_image d-flex flex-column align-items-center justify-content-center"
	>
		<% product.images.each do |image| %> <%= link_to (image_tag image,:class =>
		"img-fluid" ), show_product_path(product) %> <% end %>
	</div>
	<div class="product_content">
		<div class="product_price"><%= product.price %></div>
		<div class="product_name">
			<div><a href="#" tabindex="0"><%= product.name %></a></div>
		</div>
	</div>
</div>

<%end%>

<!-- Shop Page Navigation -->

app/views/products/brand.html.erb
<%= render "layouts/navigation/main_menu" , collection: @categories%>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<!-- Menu -->
	<div style="height: 103px;" class="home ">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="images/shop_background.jpg"></div>
		<div class="home_overlay"></div>
		<div class=" d-flex flex-column align-items-center justify-content-center">
			<h2 class="home_title"><%= params[:category_type]%></h2>
		</div>
	</div>

	<!-- Shop -->
 
	<div class="shop">
		<div class="container">
			<div class="row">
				<div class="col-lg-3">

					<!-- Shop Sidebar -->
					<div class="shop_sidebar">
						<div class="sidebar_section">
							<div class="sidebar_title">Categories</div>
							<ul class="sidebar_categories">
								<% @categories.each do |name| %>
								<% @name = name%>
								<li><%= link_to name, show_category_product_path(name) %>
								</li>
								<%end%>
							</ul>
						</div>
						<div class="sidebar_section filter_by_section">
						
							
							<div class="filter_price">
								<div id="slider-range" class="slider_range">
									<ul class="brands_list brand">
							
								
								
								</ul>
															
							</div>
								
							</div>
						</div>
						
						<div class="sidebar_section">
							
						</div>
					</div>

				</div>

				<div class="col-lg-9">
					
					<!-- Shop Content -->

					<div class="shop_content">
						<div class="shop_bar clearfix">
							<div class="shop_product_count"><span><%= @products_count%></span> products found</div>
							<div class="shop_sorting">
					
							</div>
						</div>

						<div id ="specific" class="product_grid d-flex flex-row flex-wrap">
							<div  class="product_grid_border"></div>


							<!-- Product Item -->
								<% @products.each do |product|%>
							<div class="product_item justify-content-start">
								<div class="product_border"></div>
								<div class="product_image d-flex flex-column align-items-center ">
										<% product.images.each do |image| %> 
							<%= link_to (image_tag image,:class => "img-fluid" ), show_product_path(product) %> <% end %>
								
							</div>
									
								<div class="product_content">
								<div class="product_price"><%= product.price %></div>
									<div class="product_name"><div><a href="#" tabindex="0"><%= product.name %></a></div></div>
								</div>
										<div class="product_fav"><i class="fa fa-heart" aria-hidden="true"></i></div>
								<%if product.stock == 0  %>
							<div class="text-danger d-flex">product is currently out of stock</div>
								<% end %>	
							

							
							</div>

							<%end%>

						<!-- Shop Page Navigation -->


					</div>

						<%= paginate @products, :class=> "page-link" %>

				</div>
			</div>
		</div>
	</div>

	<!-- Recently Viewed -->

	<div class="viewed">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="viewed_title_container">
						<h3 class="viewed_title">Recently Viewed</h3>
						<div class="viewed_nav_container">
							<div class="viewed_nav viewed_prev"><i class="fas fa-chevron-left"></i></div>
							<div class="viewed_nav viewed_next"><i class="fas fa-chevron-right"></i></div>
						</div>
					</div>

					<div class="viewed_slider_container">
						
						<!-- Recently Viewed Slider -->

						<div class="owl-carousel owl-theme viewed_slider">
							
							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_1.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225<span>$300</span></div>
										<div class="viewed_name"><a href="#">Beoplay H7</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_2.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$379</div>
										<div class="viewed_name"><a href="#">LUNA Smartphone</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_3.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225</div>
										<div class="viewed_name"><a href="#">Samsung J730F...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item is_new d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_4.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$379</div>
										<div class="viewed_name"><a href="#">Huawei MediaPad...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_5.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225<span>$300</span></div>
										<div class="viewed_name"><a href="#">Sony PS4 Slim</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="images/view_6.jpg" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$375</div>
										<div class="viewed_name"><a href="#">Speedlink...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Brands -->

	<div class="brands">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="brands_slider_container">
						
						<!-- Brands Slider -->

						<div class="owl-carousel owl-theme brands_slider">
							
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_1.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_2.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_3.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_4.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_5.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_6.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_7.jpg" alt=""></div></div>
							<div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="images/brands_8.jpg" alt=""></div></div>

						</div>
						
						<!-- Brands Slider Navigation -->
						<div class="brands_nav brands_prev"><i class="fas fa-chevron-left"></i></div>
						<div class="brands_nav brands_next"><i class="fas fa-chevron-right"></i></div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Newsletter -->

	<div class="newsletter">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter_container d-flex flex-lg-row flex-column align-items-lg-center align-items-center justify-content-lg-start justify-content-center">
						<div class="newsletter_title_container">
							<div class="newsletter_icon"><img src="images/send.png" alt=""></div>
							<div class="newsletter_title">Sign up for Newsletter</div>
							<div class="newsletter_text"><p>...and receive %20 coupon for first shopping.</p></div>
						</div>
						<div class="newsletter_content clearfix">
							<form action="#" class="newsletter_form">
								<input type="email" class="newsletter_input" required="required" placeholder="Enter your email address">
								<button class="newsletter_button">Subscribe</button>
							</form>
							<div class="newsletter_unsubscribe_link"><a href="#">unsubscribe</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">

				<div class="col-lg-3 footer_col">
					<div class="footer_column footer_contact">
						<div class="logo_container">
							<div class="logo"><a href="#">OneTech</a></div>
						</div>
						<div class="footer_title">Got Question? Call Us 24/7</div>
						<div class="footer_phone">+38 068 005 3570</div>
						<div class="footer_contact_text">
							<p>17 Princess Road, London</p>
							<p>Grester London NW18JR, UK</p>
						</div>
						<div class="footer_social">
							<ul>
								<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
								<li><a href="#"><i class="fab fa-twitter"></i></a></li>
								<li><a href="#"><i class="fab fa-youtube"></i></a></li>
								<li><a href="#"><i class="fab fa-google"></i></a></li>
								<li><a href="#"><i class="fab fa-vimeo-v"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-lg-2 offset-lg-2">
					<div class="footer_column">
						<div class="footer_title">Find it Fast</div>
						<ul class="footer_list">
							<li><a href="#">Computers & Laptops</a></li>
							<li><a href="#">Cameras & Photos</a></li>
							<li><a href="#">Hardware</a></li>
							<li><a href="#">Smartphones & Tablets</a></li>
							<li><a href="#">TV & Audio</a></li>
						</ul>
						<div class="footer_subtitle">Gadgets</div>
						<ul class="footer_list">
							<li><a href="#">Car Electronics</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-2">
					<div class="footer_column">
						<ul class="footer_list footer_list_2">
							<li><a href="#">Video Games & Consoles</a></li>
							<li><a href="#">Accessories</a></li>
							<li><a href="#">Cameras & Photos</a></li>
							<li><a href="#">Hardware</a></li>
							<li><a href="#">Computers & Laptops</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-2">
					<div class="footer_column">
						<div class="footer_title">Customer Care</div>
						<ul class="footer_list">
							<li><a href="#">My Account</a></li>
							<li><a href="#">Order Tracking</a></li>
							<li><a href="#">Wish List</a></li>
							<li><a href="#">Customer Services</a></li>
							<li><a href="#">Returns / Exchange</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="#">Product Support</a></li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</footer>

	<!-- Copyright -->

	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col">
					
					<div class="copyright_container d-flex flex-sm-row flex-column align-items-center justify-content-start">
						<div class="copyright_content"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy; All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</div>
						<div class="logos ml-sm-auto">
							<ul class="logos_list">
								<li><a href="#"><img src="images/logos_1.png" alt=""></a></li>
								<li><a href="#"><img src="images/logos_2.png" alt=""></a></li>
								<li><a href="#"><img src="images/logos_3.png" alt=""></a></li>
								<li><a href="#"><img src="images/logos_4.png" alt=""></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/products/brand.js.erb
$("#specific").html("<%= j render(:partial => 'products/brand') %>")

app/views/products/category_mgmt.html.erb
<div class="d-flex align-items-right">
    <div class="button banner_button">
          <%= link_to "Add category"  %>
        </div>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category_type</th>
     

    </tr>
  </thead>
  <tbody>
  	<% @all_categories.each do |category| %>
    <tr>
      <th scope="row"><%= category.id %></th>
      <td><%= category.category_type%></td>
      
   
      
    </tr>
   
<%end%>

  </tbody>

</table>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Edit product</h1>
<%= render 'products/form' %>

app/views/products/price.js.erb
$("#specific").html("<%= j render(:partial => 'products/price') %>")

app/views/products/product_show.html.erb
<div class="d-flex align-items-right">
    <div class="button banner_button">
          <%= link_to "Add product" , new_product_path %>
        </div>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Product Image</th>
      
      <th scope="col">description</th>
      <th scope="col">price</th>
      <th scope="col">Color</th>
      <th scope="col">Stock</th>
      <th scope="col">Status</th>
      <th scope="col">Discount</th>
      <th scope="col">Brand</th>
      
      <th scope="col">Model</th>
      <th scope="col">Model Year</th>
      <th scope="col">Connector type</th>
      <th scope="col">Memory Storage</th>
      <th scope="col">Operating System</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  	<% @products.each do |product| %>
    <tr>
      <th scope="row"><%= product.id %></th>
      <td><%= product.name%></td>
      <td>    <% product.images.each do |image| %> <%= image_tag image,:class =>
      "img-fluid" %> <% end %></td>
      
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.color %></td>
      <td><%= product.stock %></td>
      <td><%= product.status %></td>
      <td><%= product.discount %></td>
      <td><%= product.brand %></td>
      <td><%= product.model %></td>
      <td><%= product.model_year %></td>
      <td><%= product.connector_type %></td>
      <td><%= product.memoryStorage %></td>
      <td><%= product.operatingSystem %></td>
      <td><%=link_to "edit" , edit_product_path(product)%></td>
      <td><%=link_to "delete" , product_path(product), method: :delete, data: {confirm: "Are you Sure?"}%></td>
      
      
    </tr>
   
<%end%>

  </tbody>

</table>
 <%= paginate @products%>

app/views/products/show.html.erb
<%= javascript_include_tag "jquery.raty" %>

<div class="container fill_height">
	<div class="row align-items-center">
		<div class="col-8">
			<% @product.images.each do |image| %> <%= image_tag image,:id => "zoom_01",:class =>
			'img-fluid',:data_zoom_image => image %> <% end %>
		</div>

		<div class="col-4">
			<div class="">
				<h3 class=""><b><%= @product.name %></b></h3>
				<span>
					<span class="text-danger">₹</span>
					<span class="banner_price"><%= @product.price %></span><br />
					<span>
						<% if @product.discount == 0 %>
						<p>Discount not available</p>
						<% else %>
						<p>Discount <%= @product.discount %></p>
						<% end %>
					</span>
				</span>

				<div class="d-flex">
					<p>color:</p>
					<div class="ml-1"><%= @product.color %></div>
				</div>
				<div class="d-flex">
					Sold By :
					<div class="ml-1"><%= @product.sold_by %></div>
				</div>

				<div><b> Brand : </b> <%= @product.brand %></div>
				<div><b> Memory Storage : </b> <%= @product.memoryStorage %></div>
				<div><b> Operating System : </b> <%= @product.operatingSystem %></div>
				<div>
					<b> About this item :</b><br />
					<li><%= @product.description %></li>
				</div>
				<div>
				 <div class="review-rating" data-score = "<%= @avg_rating %>"></div>
				</div>
				<%if @product.stock == 0 %>
				<div class="text-danger">product is currently out of stock</div>
          <% @category_type=Product.joins(:category).where(category_id:@product.category_id,id:@product.id).pluck("categories.category_type") %>
        <div class="mt-3">
        <b><%= link_to "view similar products", show_brand_product_path(@product.brand,@category_type)%></b>
        <div>

				<%else%>
				<div class="button banner_button">
					<%= link_to "Add to cart", add_to_cart_path(@product), method: :put %>
				</div>
				<% end %>
      
        <div class="button banner_button">
					<%= link_to "Add to wishlist", add_to_wishlist_path(@product), id: "remote_link",remote:
					true %>
				</div>
				<div class="button banner_button">
					<%= link_to "write a review ", new_review_path(@product) %>
				</div>
				<div class="text-danger my-4">
				<%= flash[:notice]%>
					
				</div>
				<!-- <div class="button banner_button">
				<%= link_to "view all review ", all_review_path(@product) %>
			</div> -->
			</div>
		</div>
	</div>
</div>
<%if @review.present?%> <%= render template: 'reviews/index'%> 
<%else%>
<h3 class="ml-3"> No reviews given yet</h3>
<%end%>
<div></div>

	
<script src='https://cdnjs.cloudflare.com/ajax/libs/elevatezoom/3.0.8/jquery.elevatezoom.min.js'></script>
<script>
$("#zoom_01").elevateZoom({
	  cursor: "crosshair",
	  easing: true
});


  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });

</script>

app/views/products/sort.js.erb
$("#specific").html("<%= j render(:partial => 'products/sort') %>")